### ISSUE TITLE
打开网站白屏，打开视频黑屏

### ISSUE THREAD

**Issue by yadex** [manateelazycat/emacs-application-framework#23]
小白一个，按照教程安装。但是出了问题
![2018-07-18-201346_1366x768_scrot](https://user-images.githubusercontent.com/20081672/42880525-31aa88fa-8ac7-11e8-85bc-d67c8f0d608f.png)
![2018-07-18-201301_1366x768_scrot](https://user-images.githubusercontent.com/20081672/42880526-31e11596-8ac7-11e8-8ca7-5aafaf528148.png)

**Comment by yadex** [comment]
打开markdown出现了这种错误
![2018-07-18-201750_1366x768_scrot](https://user-images.githubusercontent.com/20081672/42880695-b93c1ce8-8ac7-11e8-9f3e-e842d21756e0.png)

**Comment by yadex** [comment]
(python3:5980): Gtk-[1;33mWARNING[0m **: [34m20:17:27.922[0m: 无法在模块路径中找到主题引擎：“murrine”，
EAF process start.
Traceback (most recent call last):
  File "/home/wxn/.emacs.d/emacs-application-framework/eaf.py", line 79, in create_app
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wxn/.emacs.d/emacs-application-framework/app/markdownpreviewer/buffer.py", line 25, in <module>
    from PyQt5.QtWebKitWidgets import QWebView, QWebPage
ImportError: libQt5WebKitWidgets.so.5: 无法打开共享对象文件: 没有那个文件或目录

**Comment by manateelazycat** [comment]
因为你系统的 PyQt5 已经没有了 WebKit 模块， 我最新的补丁已经修复了问题， 从 WebKit 迁移到 QtWebEngine.

你更新到最新尝试一下， 如果还有问题， 请重新打开问题。
