### ISSUE TITLE
Can't run eaf-demo. ImportError: cannot import name 'QtWebEngineWidgets'

### ISSUE THREAD

**Issue by HapCoderWei** [manateelazycat/emacs-application-framework#27]
Ubuntu 16.04 LTS
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-21 on lcy01-07, modified by Debian

When I run eaf-open with a URL or eaf-demo, it just displayed "*eaf* exited abnormally with code 1" and failed. Below is the error info from \*eaf\* buffer.
```
Traceback (most recent call last):
  File "/home/wei/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed
  File "/home/wei/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser_buffer import BrowserBuffer
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser_buffer.py", line 22, in <module>
    from core.browser import BrowserView, webview_scroll
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser.py", line 23, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets'
Traceback (most recent call last):
  File "/home/wei/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed
  File "/home/wei/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser_buffer import BrowserBuffer
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser_buffer.py", line 22, in <module>
    from core.browser import BrowserView, webview_scroll
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser.py", line 23, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets'
Traceback (most recent call last):
  File "/home/wei/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed
  File "/home/wei/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser_buffer import BrowserBuffer
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser_buffer.py", line 22, in <module>
    from core.browser import BrowserView, webview_scroll
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser.py", line 23, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets'
Traceback (most recent call last):
  File "/home/wei/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed
  File "/home/wei/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser_buffer import BrowserBuffer
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser_buffer.py", line 22, in <module>
    from core.browser import BrowserView, webview_scroll
  File "/home/wei/.emacs.d/emacs-application-framework/core/browser.py", line 23, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets'
```
非常感谢你的代码
Awesome Works!

**Comment by manateelazycat** [comment]
请通过 pip 安装 PyQt5

sudo pip install pyqt5

**Comment by manateelazycat** [comment]
成功通过 pip 安装了 PyQt5 以后， 就可以启动了。 如果安装后还有问题， 再重新打开问题。

首页有安装方法
