### ISSUE TITLE
*eaf* exited abnormally with code 1

### ISSUE THREAD

**Issue by 275761919** [manateelazycat/emacs-application-framework#32]
在 ArchLinux 上装的 Emacs-26.1, X11转发到 win10， 软件为 Mobaxterm

`eaf-open` 打开pdf或者图片时都出现这个错误，打开其他格式估计也一样。

`*eaf* `中的内容：
```
Traceback (most recent call last):
  File "/home/lyf/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/lyf/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser_buffer import BrowserBuffer
  File "/home/lyf/.emacs.d/emacs-application-framework/core/browser_buffer.py", line 22, in <module>
    from core.browser import BrowserView, webview_scroll
  File "/home/lyf/.emacs.d/emacs-application-framework/core/browser.py", line 25, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineContextMenuData
ImportError: libsmime3.so: cannot open shared object file: No such file or directory
```

并且不知道被哪个包影响了，`eaf-open` 时补全提示始终带有本机路径，无法正常输入网址，推测可能是`ivy`.

**Comment by HapCoderWei** [comment]
我也遇到了类似的问题,打开eaf-demo时总是提示`exited abnormal with code 1`
我的系统是Ubuntu 16.04LTS, GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-21 on lcy01-07, modified by Debian
*eaf*中的报错信息为:
```
Traceback (most recent call last):
  File "/home/wei/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed
  File "/home/wei/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 22, in <module>
    from PyQt5.QtCore import QUrl
ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices
```
同样我使用`eaf-open`补全时目录始终带有本机路径,需要手动删除才能输入网址或其他内容

**Comment by manateelazycat** [comment]
@275761919 libsmime3.so 的问题是因为 pyqt5 包安装的有问题, 可以用 sudo pacman -Fs 搜索一下, 看看哪个包提供的, 安装一下依赖包就可以了.

@HapCoderWei 请确保正确安装 pyqt5

补全带路径是你们Emacs自己配置有问题, 特别是有很多 Spacemacs 的用户反映 Spacemacs 的默认配置就有问题, 请使用 emacs -Q 来排除自己的配置文件问题.

这个issue问题都是 pyqt5 没有正确安装, 以及 emacs 自己的配置有问题导致自动添加不必要的路径前缀, 请使用 emacs -Q 排除.

**Comment by BonfaceKilz** [comment]
How was this solved in English? I'm facing the same problem.

**Comment by manateelazycat** [comment]
Please install PyQt5 with pip with newest version, and use "emacs -Q" for test
