### ISSUE TITLE
qtwebengine seg fault

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#352]
Mentioned in #310 , but this deserves its own issue.

```
M-x emacs-version
GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-05-22
```

```
$ yay -Qi python-pyqtwebengine | grep Version
Version         : 5.15.0-2
$ yay -Qi qt5-webengine | grep Version
Version         : 5.15.0-5
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe4378700 (LWP 113737)]
[New Thread 0x7fffe29ab700 (LWP 113738)]
[New Thread 0x7fffdbfff700 (LWP 113739)]
[New Thread 0x7fffdb66e700 (LWP 113740)]
[New Thread 0x7fffdacdd700 (LWP 113741)]
[New Thread 0x7fffda34c700 (LWP 113742)]
[Detaching after fork from child process 113743]
EAF process starting...
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 508, resource id: 0, major code: 20 (GetProperty), minor code: 0
[New Thread 0x7fffcec04700 (LWP 113751)]
[Detaching after fork from child process 113752]
[Detaching after fork from child process 113753]
[New Thread 0x7fffce273700 (LWP 113756)]
[New Thread 0x7fffcd8e2700 (LWP 113757)]
[New Thread 0x7fffccf51700 (LWP 113758)]
[New Thread 0x7fffc7fff700 (LWP 113759)]
[New Thread 0x7fffc766e700 (LWP 113760)]
[New Thread 0x7fffc6cdd700 (LWP 113761)]
[New Thread 0x7fffc634c700 (LWP 113762)]
[New Thread 0x7fffc59bb700 (LWP 113763)]
[New Thread 0x7fffc502a700 (LWP 113764)]
[New Thread 0x7fff8ffff700 (LWP 113765)]
[New Thread 0x7fff8f66e700 (LWP 113766)]
[New Thread 0x7fff8ecdd700 (LWP 113767)]
[New Thread 0x7fff8e34c700 (LWP 113768)]
[New Thread 0x7fff8d9bb700 (LWP 113769)]
Session is not restored, as no data present in session file.
[New Thread 0x7fff77fff700 (LWP 113770)]

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffebb010e0 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
#0  0x00007fffebb010e0 in  () at /usr/lib/libQt5WebEngineCore.so.5
#1  0x00000078ffffc910 in  ()
#2  0x0000000000000000 in  ()
```

Downgrading to 5.14 was a workaround, but it does not work anymore.

**Comment by manateelazycat** [comment]
I think it's system dependency problem, not EAF bug.

I also upgrade to newest package in Arch, works well.

**Comment by manateelazycat** [comment]
This last problem can not be reproduced
