### ISSUE TITLE
segmentation fault with dbus issue

### ISSUE THREAD

**Issue by HumHongeKamyaab** [manateelazycat/emacs-application-framework#390]
I am using `Ubuntu 18.04 LTS` and following emacs,
```
This is GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)
 of 2017-09-22, modified by Debian
```

I am getting following segmentation fault while using eaf-browser,
```
[EAF] *eaf* segmentation fault (core dumped)
dbus-call-method: D-Bus error: "Message recipient disconnected from message bus without replying"
dbus-call-method: D-Bus error: "The name com.lazycat.eaf was not provided by any .service files" [3 times]
```

Can someone help me in this regard ...

**Comment by HumHongeKamyaab** [comment]
update
*eaf* buffer
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdd17d700 (LWP 8513)]
[New Thread 0x7fffd36ff700 (LWP 8514)]
[New Thread 0x7fffd2ead700 (LWP 8515)]
[New Thread 0x7fffd13c0700 (LWP 8516)]
[New Thread 0x7fffc1345700 (LWP 8518)]
[New Thread 0x7fffc0af3700 (LWP 8519)]
[New Thread 0x7fffbbfff700 (LWP 8520)]
[New Thread 0x7fffbb7ad700 (LWP 8521)]
EAF process starting...
[New Thread 0x7fffaffff700 (LWP 8534)]
[New Thread 0x7fffaf7ad700 (LWP 8539)]
[New Thread 0x7fffaef5b700 (LWP 8540)]
[New Thread 0x7fffae709700 (LWP 8541)]
[New Thread 0x7fffadeb7700 (LWP 8542)]
[New Thread 0x7fffad665700 (LWP 8543)]
[New Thread 0x7ffface13700 (LWP 8544)]
[New Thread 0x7fff8bfff700 (LWP 8545)]
[New Thread 0x7fff8b7ad700 (LWP 8546)]
[New Thread 0x7fff8af5b700 (LWP 8547)]
[New Thread 0x7fff8a709700 (LWP 8548)]
[New Thread 0x7fff89eb7700 (LWP 8549)]
[New Thread 0x7fff89665700 (LWP 8550)]
[New Thread 0x7fff88e13700 (LWP 8551)]
[New Thread 0x7fff6bfff700 (LWP 8552)]
[New Thread 0x7fff6b7ad700 (LWP 8553)]
Session is not restored, as no data present in session file.
[New Thread 0x7fff69492700 (LWP 8564)]
js: Uncaught SyntaxError: Identifier 'axs' has already been declared
[New Thread 0x7fff5ad3e700 (LWP 8578)]
[New Thread 0x7fff5a4ec700 (LWP 8579)]
js: Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
js: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
[New Thread 0x7fff59a1a700 (LWP 8581)]
[New Thread 0x7fff58976700 (LWP 8582)]
[New Thread 0x7fff591c8700 (LWP 8583)]
[1:15:0904/112440.366851:ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[1:15:0904/112440.366947:ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[1:1:0904/112440.435289:ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
[1:1:0904/112440.435546:ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
[1:15:0904/112440.496873:ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[1:1:0904/112440.681022:ERROR:render_media_log.cc(27)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS

Thread 14 "Chrome_IOThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffadeb7700 (LWP 8542)]
0x00007fffece96f37 in ?? () from /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5
#0  0x00007fffece96f37 in  () at /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5
#1  0x00007fffadeb6840 in  ()
#2  0x00007fff983f6fd0 in  ()
#3  0x00007fffadeb67e0 in  ()
#4  0x00007fffece88faf in  () at /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5
#5  0x00007fffece8cbd0 in  () at /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5
#6  0x00007fffadeb67a0 in  ()
#7  0x0000000000000000 in  ()

```

**Comment by manateelazycat** [comment]
I believe it's a bug of WebEngine in Ubuntu.

Looks something wrong with ffmpeg.

Sorry I can't help you.
