### ISSUE TITLE
Unable to open terminal

### ISSUE THREAD

**Issue by Phate6660** [manateelazycat/emacs-application-framework#452]
**Describe the bug**
The terminal opens for a split second before closing.

**To Reproduce**
Clone the master branch, load and require `eaf`, attempt to run `eaf-open-terminal`, bug ensues.

**Expected behavior**
The terminal should open, and stay open.

**Versions (please complete the following info):**
 - Distro and DE/WM: Gentoo, herbstluftwm
 - Versions of Dependencies:
    + `PyQt5`: 5.14.2
    + `PyQt5-sip`: 4.19.24
    + `dbus-python`: 1.2.16-r1
    + `PyQtWebEngine`: 5.14.0
    + `wmctrl`: 1.07-r2
    + `NodeJS`: 12.19.1
 - `M-x emacs-version`: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, X toolkit) of 2020-11-29

**Additional context**
`Messages` buffer:

```
[EAF] Process starting...
[EAF/terminal] Opening /home/valley/
[EAF] *eaf* aborted
[EAF] Process already terminated.
```

Un-named buffer with EAF output:

```
EAF process starting...
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /index.html HTTP/1.1" 200 -
Session is not restored, as no data present in session file.
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm/lib/xterm.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-attach/lib/xterm-addon-attach.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-fit/lib/xterm-addon-fit.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-search/lib/xterm-addon-search.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-web-links/lib/xterm-addon-web-links.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /dark_theme.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm/css/xterm.css HTTP/1.1" 200 -
js: WebSocket connection to 'ws://127.0.0.1:59399/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Traceback (most recent call last):
  File "/home/valley/.emacs.d/emacs-application-framework/app/terminal/buffer.py", line 95, in focus_terminal
    QApplication.sendEvent(self.buffer_widget.focusProxy(), event)
RuntimeError: wrapped C/C++ object of type BrowserView has been deleted
```

**Comment by Phate6660** [comment]
I have found the issue!

Running `node server.js` within `/app/terminal` resulted in:

```
Error: The module '/home/valley/.emacs.d/emacs-application-framework/app/terminal/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/valley/.emacs.d/emacs-application-framework/app/terminal/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

After running `npm rebuild` and trying `eaf-open-terminal` again, it worked.
