### ISSUE TITLE
eaf-pdf 按如下操作直接 [EAF] *eaf* 已放弃 (core dumped)

### ISSUE THREAD

**Issue by loyalpartner** [manateelazycat/emacs-application-framework#502]
复现方法

1. 打开任意 pdf 文件，eaf-proxy-zoom_out 到最大，关掉文件，再次打开
2. 拉到最后一页
3. M-x eaf-proxy-zoom_in
4. 点击 pdf 底部

https://ibb.co/TvKbkjX

pdf 
```
Traceback (most recent call last):
  File "/home/lee/.emacs.d/.local/straight/repos/emacs-application-framework/app/pdf-viewer/buffer.py", line 1294, in eventFilter
    self.hover_annot()
  File "/home/lee/.emacs.d/.local/straight/repos/emacs-application-framework/app/pdf-viewer/buffer.py", line 1138, in hover_annot
    page = self.document[page_index]
  File "/home/lee/.local/lib/python3.9/site-packages/fitz/fitz.py", line 4977, in __getitem__
    raise IndexError("page not in document")
```

**Comment by manateelazycat** [comment]
Fixed in newest version, thanks for report.

**Comment by loyalpartner** [comment]
如果pdf文件只有一个页面，还是会触发这个错误
