### ISSUE TITLE
Windows下mermaid预览失败

### ISSUE THREAD

**Issue by vconcat** [manateelazycat/emacs-application-framework#533]
**Describe the bug**
app mermaid预览mmd文件失败。

**To Reproduce**

打开如下内容的文件
```
graph TD
      A[Hard] -->|Text| B(Round)
      B --> C{Decision}
      C -->|One| D[Result 1]
      C -->|Two| E[Result 2]
```
然后`eaf-open`此mmd文件。

**Expected behavior**

右侧预览窗口能正常渲染

**Versions (please complete the following info):**
 - Distro and DE/WM: Windows 10，只包括eaf的最小配置
 - Versions of Dependencies:
 - M-x emacs-version: 27.1

**Screenshots**

**Additional context**

commit https://github.com/manateelazycat/emacs-application-framework/commit/c3bfef1591865beb96998490bb034d325dc7e64d

修改了`eaf.py`，如下：
```
    def webengine_include_private_codec(self):
        ''' Return bool of whether the QtWebEngineProcess include private codec. '''
        path = os.path.join(QLibraryInfo.location(QLibraryInfo.LibraryExecutablesPath), "QtWebEngineProcess")
        #return self.get_command_result("ldd {} | grep libavformat".format(path)) != ""
        return True
```
否则会报告`ldd`找不到之类的错误。

*eaf* buffer内容
```
Traceback (most recent call last):
  File "c:\Users\wsw\.emacs.d\straight\build\eaf\core\utils.py", line 57, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "c:/Users/wsw/.emacs.d/straight/build/eaf/eaf.py", line 312, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'f45a-b4fa-def2-3519-d677-60c4-95ce'

Process *eaf* exited abnormally with code 9
Traceback (most recent call last):
  File "c:\Users\wsw\.emacs.d\straight\build\eaf\core\utils.py", line 57, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "c:/Users/wsw/.emacs.d/straight/build/eaf/eaf.py", line 312, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'f45a-b4fa-def2-3519-d677-60c4-95ce'

Process *eaf* exited abnormally with code 9

```

**Comment by xhcoding** [comment]
提了一个 PR 修复 inotify 的问题。

另外 mmd 要用 markdown 格式写，不然只能渲染出来文字

```
```mermaid
graph TD
      A[Hard] -->|Text| B(Round)
      B --> C{Decision}
      C -->|One| D[Result 1]
      C -->|Two| E[Result 2]
\```
```
