### ISSUE TITLE
偶尔有些pdf文件打不开

### ISSUE THREAD

**Issue by tumashu** [manateelazycat/emacs-application-framework#556]
偶尔有pdf文件会报这种错误，我搞不清楚是哪方面的bug。。。
```
Traceback (most recent call last):
  File "/home/feng/projects/emacs-packages/emacs-application-framework/core/utils.py", line 57, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/feng/projects/emacs-packages/emacs-application-framework/eaf.py", line 131, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/home/feng/projects/emacs-packages/emacs-application-framework/eaf.py", line 178, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/feng/projects/emacs-packages/emacs-application-framework/eaf.py", line 192, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/home/feng/projects/emacs-packages/emacs-application-framework/app/pdf-viewer/buffer.py", line 43, in __init__
    self.add_widget(PdfViewerWidget(url, config_dir, QColor(0, 0, 0, 255), buffer_id, emacs_var_dict))
  File "/home/feng/projects/emacs-packages/emacs-application-framework/app/pdf-viewer/buffer.py", line 245, in __init__
    self.first_pixmap = self.document.getPagePixmap(0)
  File "/home/feng/.local/lib/python3.7/site-packages/fitz/utils.py", line 485, in getPagePixmap
    return doc[pno].getPixmap(matrix=matrix, colorspace=colorspace,
  File "/home/feng/.local/lib/python3.7/site-packages/fitz/fitz.py", line 2833, in __getitem__
    raise IndexError("bad page number(s)")
IndexError: bad page number(s)

```

**Comment by manateelazycat** [comment]
PDF 文件发一下？

**Comment by tumashu** [comment]
我靠，我找到原因了，是这个pdf不知道什么原因损坏了。。。 汗！

**Comment by tumashu** [comment]
不好意思！
