### ISSUE TITLE
[BUG] eaf exited with code 1

### ISSUE THREAD

**Issue by Novite5** [manateelazycat/emacs-application-framework#587]
**Describe the bug**
All commands from eaf don't work normally, get the result:
```
Qt: Session management error: Could not open network socket
EAF process starting...
Traceback (most recent call last):
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/eaf.py", line 193, in create_buffer
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/app/camera/buffer.py", line 25, in <module>
    from PyQt5.QtMultimedia import QCameraInfo, QCamera, QCameraImageCapture
ImportError: libQt5Multimedia.so.5: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Traceback (most recent call last):
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/eaf.py", line 255, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'd0e4-848e-1ba2-e5af-07df-61ea-19e3'

Process *eaf* abgebrochen (core dumped)
Qt: Session management error: Could not open network socket
Traceback (most recent call last):
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/eaf.py", line 497, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/eaf.py", line 66, in __init__
    init_epc_client(int(emacs_server_port))
  File "/home/weber/.emacs.d/private/local/emacs-application-framework/core/utils.py", line 195, in init_epc_client
    epc_client = EPCClient(("localhost", emacs_server_port), log_traceback=True)
  File "/usr/lib/python3.9/site-packages/epc/client.py", line 95, in __init__
    self.connect(socket_or_address)
  File "/usr/lib/python3.9/site-packages/epc/client.py", line 110, in connect
    self.socket = socket.create_connection(socket_or_address)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Verbindungsaufbau abgelehnt

Process *eaf* exited abnormally with code 1

```

**To Reproduce**
This occurs after pull the newest commit, on `d7072de` works well.

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: Archlinux Xorg Gnome 3.38.4
 - Versions of Dependencies: git-2.30.1-1 nodejs-15.8.0-1 python-pyqt5-5.15.2-3 python-pyqt5-sip-12.8.1-3 python-pyqt5-webengine-5.15.2-1 wmctrl-1.07-6 xdotool-3.20160805.1-3 python-qrcode-6.1-6 aria2-1.35.0-2 python-qtconsole-5.0.1-2 pymupdf-1.18.8 python-epc-0.0.5 python-retrying-1.3.3 python-six-1.15.0
 - M-x emacs-version: 27.1

Notes: please add a corresponding GitHub Label so future people can find this issue easier.

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
I have commit new patch https://github.com/manateelazycat/emacs-application-framework/commit/0c2c91f1bc199eb96679daaa7b7ff94145864e0e

Can you git pull and try again?

Thanks for report. ;)

**Comment by Novite5** [comment]
Yes, it has been fixed. 
Thank you for your great work!
