### ISSUE TITLE
markdown-previewer fails to open with ConnectionRefused error

### ISSUE THREAD

**Issue by aahamlin** [manateelazycat/emacs-application-framework#591]
This feature was working nicely for the past month or two but today I cannot open previews.

`M-x eaf-open`
Choose my markdown file and an empty buffer is displayed. Stack trace from *eaf* error buffer below.

(An aside, it would be super awesome if there was an M-x eaf-open-buffer function added to avoid having to choose the file name that I already have opened.)

## Stacktrace

```
EAF process starting...
Traceback (most recent call last):
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/eaf.py", line 133, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/eaf.py", line 194, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/app/markdown-previewer/buffer.py", line 52, in __init__
    self.render()
  File "/home/ahamlin/.local/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ahamlin/.local/lib/python3.8/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/ahamlin/.local/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ahamlin/.local/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/app/markdown-previewer/buffer.py", line 76, in render
    with urlopen(url) as f:
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/ahamlin/.pyenv/versions/3.8.7/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

Process *eaf* aborted (core dumped)
```

**Comment by MatthewZMD** [comment]
Try to `git pull` and run the install script again, you may be missing some latest dependencies.

**Comment by MatthewZMD** [comment]
> (An aside, it would be super awesome if there was an M-x eaf-open-buffer function added to avoid having to choose the file name that I already have opened.)

Great suggestion, try `eaf-open-this-buffer` :-)

**Comment by aahamlin** [comment]
The open-this-buffer works nice. Thanks. Unfortunately I’m still running jnto the connection issue. 

Today I tried downgrading from python 3.8.9 to 3.8.6 and 3.7.9. Both of which had worked in the past for me. But still seeing the same issue. 

As I’m thinking back, there was a recent TLS change when I built emacs on this system. (emacs 27.1) could there be some certificate issue or permissions on a socket or something?

Not sure what other logs to provide to help or how to try debugging... other than maybe trying to run the python by hand at the command line?

**Comment by mackong** [comment]
please first check if the node process start succeed.
```
ps aux | grep render.js
```

if the node process start succeed, then try increase the *stop_max_attemp_number* argument at *markdown_previewer/buffer.py:68*. then restart eaf and retry.

if the node process not start succeed, please try
```
cd mardkown_previewer
node render.js 8080
```
and see any errors.

**Comment by aahamlin** [comment]
Thanks for the troubleshooting steps. I have it resolved now. 

Here is what I discovered:

```
$ node render.js 8080
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module '@shd101wyy/mume'
Require stack:
- /home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/app/markdown-previewer/render.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/app/markdown-previewer/render.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ahamlin/.emacs.d/site-elisp/emacs-application-framework/app/markdown-previewer/render.js'
  ]
}
```

Changing into the markdown-previewer directory and running `npm install` fixed the problems.

After this the missing node_modules directory was created with the mume module.

I found the install-eaf.sh line that cause the problem was this:
branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
if [[ $branch == "master" ]]; then
    echo "Installing npm dependencies..."
    npm install
fi

The branch is "(HEAD detached at a46f31a)" on my system, likely caused by EAF being installed as a submodule?

I did not run into this problem on the other system I setup EAF but do not remember specifically doing any different steps. So I don't know if the install script should do something different or the instructions I followed from M-Emacs could be clearer or if I was just half asleep the day I setup this new system. :)

**Comment by MatthewZMD** [comment]
> I found the install-eaf.sh line that cause the problem was this:
> branch=$(git branch | sed -n -e 's/^* (.*)/\1/p')
> if [[ $branch == "master" ]]; then
> echo "Installing npm dependencies..."
> npm install
> fi
> 
> The branch is "(HEAD detached at [a46f31a](https://github.com/manateelazycat/emacs-application-framework/commit/a46f31a1b17a93f8b5b2c4ab7c9d6f11593f1d32))" on my system, likely caused by EAF being installed as a submodule?

Thanks for spotting this issue. That was some obsolete if condition that we forgot to remove, I'll do it now.
