### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#61]
I already pip installed pyqt5 according to README `sudo pip install dbus-python PyMuPDF grip qrcode pyqt5 python-xlib`

When I try to open a pdf file, minibuffer gives this error:`*eaf* exited abnormally with code 1`

This is what I am seeing in `*eaf*` buffer:

```
Traceback (most recent call last):
  File "/home/matthewzmd/.emacs.d/site-elisp/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/matthewzmd/.emacs.d/site-elisp/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser_buffer import BrowserBuffer
  File "/home/matthewzmd/.emacs.d/site-elisp/emacs-application-framework/core/browser_buffer.py", line 22, in <module>
    from core.browser import BrowserView, webview_scroll
  File "/home/matthewzmd/.emacs.d/site-elisp/emacs-application-framework/core/browser.py", line 25, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineContextMenuData
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

[this](https://github.com/manateelazycat/emacs-application-framework/issues/32#issuecomment-408712786) and [that](https://github.com/manateelazycat/emacs-application-framework/issues/6) didn't solve the problem.

**Comment by chen-chao** [comment]
See #56 .

**Comment by MatthewZMD** [comment]
Another error seems to occur:
```
File "/home/matthewzmd/.emacs.d/site-elisp/emacs-application-framework/core/browser.py", line 25, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineContextMenuData
ImportError: /usr/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: symbol _ZSt24__throw_out_of_range_fmtPKcz version Qt_5 not defined in file libQt5Qml.so.5 with link time reference
```

**Comment by manateelazycat** [comment]
操作系统提供的 PyQt5 有问题，不是EAF本身的问题。

**Comment by MatthewZMD** [comment]
Manjaro系统, 该怎么修复呢...

**Comment by paxinla** [comment]
我也碰到同样的问题，试试: pip install PyQtWebEngine

**Comment by MatthewZMD** [comment]
> 操作系统提供的 PyQt5 有问题，不是EAF本身的问题。

今天用回了Manjaro KDE，又遇到了这个问题:
> ImportError: /usr/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: symbol _ZSt24__throw_out_of_range_fmtPKcz version Qt_5 not defined in file libQt5Qml.so.5 with link time reference

一狠心直接删掉整个PyQt5文件夹，全部重装

```
sudo rm -rf /usr/lib/python3.7/site-packages/PyQt5/
sudo pip uninstall PyQt5
sudo pip uninstall PyQt5-sip
sudo pip uninstall PyQt5WebEngine
sudo pip install PyQt5
sudo pip install PyQt5-sip
sudo pip install PyQt5WebEngine
```

Problem fixed haha

**Comment by manateelazycat** [comment]
这是 Arch 的锅，系统升级后要重新跑一遍 pip

**Comment by MatthewZMD** [comment]
哎 这问题真麻烦
