### ISSUE TITLE
`Process epc con X not running`

### ISSUE THREAD

**Issue by lebensterben** [manateelazycat/emacs-application-framework#630]
**Describe the bug**
Install all dependencies and eaf.

Try to open anything with eaf, e.g. `eaf-open-browser` or `eaf-open-terminal`.
A new buffer is opened. (The minibuffer shows "Opening XXX" when it's opening a URL)
Nothing shows up.

Press any key and the minibuffer shows "Process epc con X not running"

**Versions (please complete the following info):**
 - Distro and DE/WM: Clear Linux, XMonad
 - Versions of Dependencies: Latest
 - M-x emacs-version: 27.2

**Comment by MatthewZMD** [comment]
What does the `*eaf*` buffer display?

**Comment by lebensterben** [comment]
```
EAF process starting...
Traceback (most recent call last):
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/eaf.py", line 133, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/eaf.py", line 194, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/app/browser/buffer.py", line 35, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, config_dir, arguments, emacs_var_dict, module_path, False)
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/core/browser.py", line 612, in __init__
    self.add_widget(BrowserView(buffer_id, config_dir))
  File "/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/core/browser.py", line 71, in __init__
    self.dark_mode_js = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),
FileNotFoundError: [Errno 2] No such file or directory: '/home/lucius/.emacs.d/elpa/27.2/develop/eaf-20210416.2138/node_modules/darkreader/darkreader.js'

Process *eaf* aborted (core dumped)
```

**Comment by lebensterben** [comment]
https://github.com/manateelazycat/emacs-application-framework#dependency-list

There's no mentioning of NPM package dependency here.
