### ISSUE TITLE
Qt: Session management error: Could not open network socket

### ISSUE THREAD

**Issue by matteha** [manateelazycat/emacs-application-framework#689]
Just installed eaf on fedora with emacs 28.0.50 (native comp, not pgtk). Some eaf applications work (e.g. eaf-open-jupyter, eaf-demo) but others dont, getting the following kinds of errors in the eaf buffer (this is on the latest commit of eaf):

Qt: Session management error: Could not open network socket
EAF process starting...
Traceback (most recent call last):
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 133, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 194, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/app/browser/buffer.py", line 35, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, config_dir, arguments, emacs_var_dict, module_path, False)
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/core/webengine.py", line 612, in __init__
    self.add_widget(BrowserView(buffer_id, config_dir))
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/core/webengine.py", line 71, in __init__
    self.dark_mode_js = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),
FileNotFoundError: [Errno 2] No such file or directory: '/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/node_modules/darkreader/darkreader.js'
Traceback (most recent call last):
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/linux/.emacs.d/.local/straight/repos/emacs-application-framework/eaf.py", line 256, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: 'ffbd-15f2-4c5f-b184-9ef6-663f-233f'

**Comment by matteha** [comment]
Seems to be a duplicate of https://github.com/manateelazycat/emacs-application-framework/issues/587 but still getting the error on the latest commit.

**Comment by matteha** [comment]
Fixed it by manually running ./eaf_install.sh in the straight folder (I ran eaf-install-dependencies before).
