### ISSUE TITLE
EAF browser crashes on certain websites

### ISSUE THREAD

**Issue by TerryTsao** [manateelazycat/emacs-application-framework#697]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 47410]
[New Thread 0x7fffe5c03700 (LWP 47411)]
Gtk-[1;32mMessage[0m: [34m11:00:02.193[0m: Failed to load module "unity-gtk-module"
[New Thread 0x7fffdfc1c700 (LWP 47412)]
[New Thread 0x7fffdf28b700 (LWP 47413)]
[New Thread 0x7fffdd939700 (LWP 47414)]
[New Thread 0x7fffdcfa8700 (LWP 47415)]
[New Thread 0x7fffd6227700 (LWP 47416)]
[Detaching after fork from child process 47417]
EAF process starting...
[New Thread 0x7fffd5896700 (LWP 47429)]
[New Thread 0x7fffd4f05700 (LWP 47430)]
[New Thread 0x7fffbbfff700 (LWP 47431)]
[Thread 0x7fffbbfff700 (LWP 47431) exited]
[New Thread 0x7fffbbfff700 (LWP 47446)]
[Detaching after fork from child process 47447]
[Detaching after fork from child process 47448]
[Detaching after fork from child process 47449]
[New Thread 0x7fffbac69700 (LWP 47452)]
[New Thread 0x7fffba2d8700 (LWP 47453)]
[New Thread 0x7fffb9947700 (LWP 47454)]
[New Thread 0x7fffb8fb6700 (LWP 47455)]
[New Thread 0x7fffa3fff700 (LWP 47456)]
[New Thread 0x7fffa366e700 (LWP 47457)]
[New Thread 0x7fffa234c700 (LWP 47459)]
[New Thread 0x7fffa2cdd700 (LWP 47458)]
[New Thread 0x7fffa19bb700 (LWP 47460)]
[New Thread 0x7fffa102a700 (LWP 47461)]
[New Thread 0x7fff8bfff700 (LWP 47462)]
[New Thread 0x7fff8b66e700 (LWP 47463)]
[New Thread 0x7fff8acdd700 (LWP 47464)]
[New Thread 0x7fff8a34c700 (LWP 47465)]
[Detaching after fork from child process 47466]
[New Thread 0x7fff899bb700 (LWP 47467)]
[New Thread 0x7fff8902a700 (LWP 47469)]
[New Thread 0x7fff6ffff700 (LWP 47487)]
Session is not restored, as no data present in session file.
[New Thread 0x7fff6f66e700 (LWP 47491)]
[New Thread 0x7fff6ecdd700 (LWP 47493)]
[Thread 0x7fff6ecdd700 (LWP 47493) exited]
[New Thread 0x7fff6ecdd700 (LWP 47495)]
[Thread 0x7fff6ecdd700 (LWP 47495) exited]
[New Thread 0x7fff6ecdd700 (LWP 47496)]
[Thread 0x7fff6ecdd700 (LWP 47496) exited]
[New Thread 0x7fff6ecdd700 (LWP 47515)]
[Thread 0x7fff6ecdd700 (LWP 47515) exited]
[New Thread 0x7fff6ecdd700 (LWP 47516)]
[Thread 0x7fff6ecdd700 (LWP 47516) exited]
[New Thread 0x7fff6ecdd700 (LWP 47519)]

Thread 16 "ThreadPoolForeg" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa3fff700 (LWP 47456)]
0x00007fffeef92b97 in ?? () from /data/terrytsao/envs/base/lib/python3.8/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5
#0  0x00007fffeef92b97 in  () at /data/terrytsao/envs/base/lib/python3.8/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5
#1  0x0000000000000000 in  ()

Process *eaf* finished
```

**Describe the bug**

- EAF browser crashes on certain website on my machine
- Always crash: slack (after successful login to whichever workspace)
- Sometimes: [Emacs China](https://emacs-china.org) (can't reproduce in emacs -Q)
- And occasionally other sites (don't remember)

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

```lisp
;;; NOTE: debug.el

(require 'package)
(package-initialize)

;;; NOTE: The following three lines loads my paths.
;;; commented out for apparent reasons
;;; setq `exec-path' & `load-path'

;; (with-temp-buffer
;;   (insert-file-contents-literally "./paths.el")
;;   (eval-buffer))

(setq eaf-enable-debug t)
(require 'eaf)
(eaf-open-browser "https://clojurians.slack.com/")
```
Run from shell:
```bash
emacs -Q --load debug.el
```

**Expected behavior**

EAF does not crash.

**Versions (please complete the following info):**
 - Distro and DE/WM
 Ubuntu 20.04; GNOME Shell (returned by `eaf--get-current-desktop-name`)
 - Versions of Dependencies:
 ```
aiofiles==0.6.0
alabaster==0.7.12
appdirs==1.4.4
astor==0.8.1
Babel==2.9.0
backcall==0.2.0
bcrypt==3.2.0
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
ci-info==0.2.0
click==7.1.2
colorama==0.4.4
configobj==5.0.6
configparser==5.0.2
cryptography==3.4.7
decorator==4.4.2
docutils==0.16
epc==0.0.5
etelemetry==0.2.2
filelock==3.0.12
flatbuffers==1.12
funcparserlib==0.3.6
future==0.18.2
h11==0.12.0
httplib2==0.19.1
hy==0.19.0
idna==2.10
imagesize==1.2.0
ipykernel==5.5.5
ipython==7.22.0
ipython-genutils==0.2.0
isodate==0.6.0
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.11.2
jupyter-client==6.2.0
jupyter-core==4.7.1
lxml==4.6.3
MarkupSafe==1.1.1
nest-asyncio==1.5.1
networkx==2.5.1
nibabel==3.2.1
nipype==1.6.0
numpy==1.19.4
opencv-python==4.4.0.46
packaging==20.8
pandas==1.2.4
paramiko==2.7.2
parso==0.8.2
pathlib==1.0.1
pexpect==4.8.0
pickleshare==0.7.5
ply==3.11
powerline-status==2.7
prompt-toolkit==3.0.8
prov==2.0.0
psutil==5.8.0
ptvsd==4.3.2
ptyprocess==0.6.0
pybind11==2.6.2
pycparser==2.20
pydot==1.4.2
Pygments==2.7.3
PyMuPDF==1.18.12
PyNaCl==1.4.0
pyparsing==2.4.7
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.4
PyQtWebEngine-Qt5==5.15.2
python-dateutil==2.8.1
pytz==2020.5
pyxnat==1.4
pyzmq==22.1.0
qtconsole==5.1.0
QtPy==1.9.0
rdflib==5.0.0
requests==2.25.1
retrying==1.3.3
robotpy-cppheaderparser==5.0.11
rply==0.7.7
scipy==1.6.2
sexpdata==0.0.3
simplejson==3.17.2
six==1.15.0
snowballstemmer==2.0.0
Sphinx==3.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
starlette==0.14.2
torch==1.7.1
tornado==6.1
traitlets==5.0.5
traits==6.2.0
typing-extensions==3.7.4.3
urllib3==1.26.2
uvicorn==0.13.4
wcwidth==0.2.5
yapf==0.30.0
```
 - M-x emacs-version
 GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-12-11
native-comp branch
spacemacs develop

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
don't install pyqt5 with pip

install pyqt5 from system package repository

**Comment by TerryTsao** [comment]
Thanks! Didn't think it would make so big a difference. Thank you for your time. Closing.
