### ISSUE TITLE
Problem with PyQt5

### ISSUE THREAD

**Issue by Cletip** [manateelazycat/emacs-application-framework#704]
Hey !

I am in ubuntu 20,.04, and I have some trouble with eaf x). First of all :
- eaf worked in emacs 26.3, I am actually with the version 27.1
- I made the tutorial perfectly (I think)
- I use straight to manage my package
- I try to run eaf-open-browser and eaf-open  "afile.org", and I have this same issue :
```

Traceback (most recent call last):
  File "/home/msi/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/msi/.emacs.d/site-lisp/emacs-application-framework/app/browser/buffer.py", line 25, in <module>
    from core.webengine import BrowserBuffer
  File "/home/msi/.emacs.d/site-lisp/emacs-application-framework/core/webengine.py", line 26, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineScript, QWebEngineProfile, QWebEngineSettings
ImportError: /lib/x86_64-linux-gnu/libQt5Qml.so.5: undefined symbol: _ZN14QMetaCallEventC1EttPFvP7QObjectN11QMetaObject4CallEiPPvEPKS0_iiPiS5_P10QSemaphore, version Qt_5_PRIVATE_API

Process *eaf* exited abnormally with code 1






Traceback (most recent call last):
  File "/home/msi/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/msi/.emacs.d/site-lisp/emacs-application-framework/app/browser/buffer.py", line 25, in <module>
    from core.webengine import BrowserBuffer
  File "/home/msi/.emacs.d/site-lisp/emacs-application-framework/core/webengine.py", line 26, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineScript, QWebEngineProfile, QWebEngineSettings
ImportError: /lib/x86_64-linux-gnu/libQt5Qml.so.5: undefined symbol: _ZN14QMetaCallEventC1EttPFvP7QObjectN11QMetaObject4CallEiPPvEPKS0_iiPiS5_P10QSemaphore, version Qt_5_PRIVATE_API

Process *eaf* exited abnormally with code 1

```

I have already reinstalling emacs and PyQt5, but I don't know exactly where is the problem. 

Thank you in advance for your answers !

**Comment by manateelazycat** [comment]
Please DO NOT install PyQt5 through pip, pip version has bug, please install PyQt5 from the OS software repository.
