### ISSUE TITLE
install-eaf.sh do not install is-svg

### ISSUE THREAD

**Issue by tumashu** [manateelazycat/emacs-application-framework#709]
```
ERROR  Error: CSS minification error: Cannot find module 'is-svg'
 Require stack:
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/postcss-svgo/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano-preset-default/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/config/css.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/Service.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/bin/vue-cli-service.js. File: css/app.46b5b596.css
Error: CSS minification error: Cannot find module 'is-svg'

```

**Comment by manateelazycat** [comment]
删除 node_modules 目录，重新来一遍 install-eaf.sh ?

**Comment by tumashu** [comment]
上班的时候我试试

**Comment by tumashu** [comment]
好像不行， rm node_modules, git reset hard, git pull 之后，运行命令还有下面的错误
```
eng@debian:~/projects/emacs-packages/emacs-application-framework $ git reset --hard
HEAD 现在位于 028aef5 Replaced extra python functions into ELisp functions & added `login` keybinding (#708)
feng@debian:~/projects/emacs-packages/emacs-application-framework $ ls
app                   eaf.py                package.json
core                  fix-node-security.js  package-lock.json
docker                install-eaf-mac.sh    README.md
eaf-all-the-icons.el  install-eaf.sh        README.zh-CN.md
eaf.el                install-eaf-win32.js  requirements.txt
eaf-evil.el           install-node-apps.js  screenshot
EAF_Logo.png          LICENSE               setup.py
eaf-org.el            node_modules          tags
feng@debian:~/projects/emacs-packages/emacs-application-framework $ rm node_modules
rm: 无法删除 'node_modules': 是一个目录
feng@debian:~/projects/emacs-packages/emacs-application-framework $ rm -rf node_modules
feng@debian:~/projects/emacs-packages/emacs-application-framework $ ls
app                   eaf.py                package-lock.json
core                  fix-node-security.js  README.md
docker                install-eaf-mac.sh    README.zh-CN.md
eaf-all-the-icons.el  install-eaf.sh        requirements.txt
eaf.el                install-eaf-win32.js  screenshot
eaf-evil.el           install-node-apps.js  setup.py
EAF_Logo.png          LICENSE               tags
eaf-org.el            package.json
feng@debian:~/projects/emacs-packages/emacs-application-framework $ git pull
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 24 (delta 10), reused 18 (delta 7), pack-reused 0
展开对象中: 100% (24/24), 248.59 KiB | 381.00 KiB/s, 完成.
来自 https://github.com/manateelazycat/emacs-application-framework
   028aef5..6f3fd79  master     -> origin/master
更新 028aef5..6f3fd79
Fast-forward
 app/file-manager/README.md                         |    24 +
 app/file-manager/babel.config.js                   |     5 +
 app/file-manager/buffer.py                         |    84 +
 app/file-manager/package-lock.json                 | 26546 +++++++++++++++++++
 app/file-manager/package.json                      |    42 +
 app/file-manager/src/App.vue                       |    36 +
 app/file-manager/src/components/Main.vue           |    78 +
 app/file-manager/src/main.js                       |     8 +
 app/netease-cloud-music/eaf-netease-cloud-music.el |   183 +
 eaf.el                                             |   234 +-
 package.json                                       |     5 +-
 11 files changed, 27068 insertions(+), 177 deletions(-)
 create mode 100644 app/file-manager/README.md
 create mode 100644 app/file-manager/babel.config.js
 create mode 100644 app/file-manager/buffer.py
 create mode 100644 app/file-manager/package-lock.json
 create mode 100644 app/file-manager/package.json
 create mode 100644 app/file-manager/src/App.vue
 create mode 100644 app/file-manager/src/components/Main.vue
 create mode 100644 app/file-manager/src/main.js
 create mode 100644 app/netease-cloud-music/eaf-netease-cloud-music.el
feng@debian:~/projects/emacs-packages/emacs-application-framework $ ./install-eaf.sh 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
aria2 已经是最新版 (1.35.0-3)。
git 已经是最新版 (1:2.30.2-1)。
wmctrl 已经是最新版 (1.07-7+b1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
libglib2.0-dev 已经是最新版 (2.66.8-1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
python3-feedparser 已经是最新版 (5.2.1-3)。
python3-pyqt5 已经是最新版 (5.15.2+dfsg-3)。
python3-pyqt5.qtwebengine 已经是最新版 (5.15.2-2)。
python3-markdown 已经是最新版 (3.3.4-1)。
python3-pygit2 已经是最新版 (1.4.0+dfsg1-1)。
python3-qrcode 已经是最新版 (6.1-2)。
python3-qtconsole 已经是最新版 (5.0.2-2)。
python3-sip 已经是最新版 (4.19.25+dfsg-1)。
libtag1-dev 已经是最新版 (1.11.1+dfsg.1-3)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
Installing npm dependencies...

> emacs-application-framework@1.0.0 postinstall
> node install-node-apps.js


up to date, audited 7 packages in 913ms

found 0 vulnerabilities

up to date, audited 246 packages in 1s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 2 packages in 932ms

found 0 vulnerabilities

up to date, audited 68 packages in 1s

found 0 vulnerabilities

up to date, audited 1309 packages in 2s

25 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

up to date, audited 1325 packages in 2s

15 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

up to date, audited 1507 packages in 3s

44 packages are looking for funding
  run `npm fund` for details

20 vulnerabilities (6 low, 13 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

added 1308 packages, and audited 1309 packages in 8s

25 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (12 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

up to date, audited 1535 packages in 3s

2 packages are looking for funding
  run `npm fund` for details

22 vulnerabilities (5 low, 16 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> vue-demo@0.1.0 build
> vue-cli-service build


⠋  Building for production...

 DONE  Compiled successfully in 1594ms                               上午8:12:05

  File                                 Size               Gzipped

  dist/js/chunk-vendors.92c2867a.js    89.66 KiB          32.14 KiB
  dist/js/app.8cb0e284.js              2.87 KiB           1.32 KiB
  dist/css/app.606858ee.css            0.27 KiB           0.20 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  

> system-monitor@0.1.0 build
> vue-cli-service build


 ERROR  Error: CSS minification error: Cannot find module 'is-svg'
 Require stack:
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/postcss-svgo/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano-preset-default/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/config/css.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/Service.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/bin/vue-cli-service.js. File: css/app.46b5b596.css
Error: CSS minification error: Cannot find module 'is-svg'
Require stack:
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/postcss-svgo/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano-preset-default/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/config/css.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/Service.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/bin/vue-cli-service.js. File: css/app.46b5b596.css
    at /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21
    at async Promise.all (index 0)
child_process.js:674
    throw err;
    ^

Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at installVueApps (/home/feng/projects/emacs-packages/emacs-application-framework/install-node-apps.js:28:9)
    at Object.<anonymous> (/home/feng/projects/emacs-packages/emacs-application-framework/install-node-apps.js:45:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 14760,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /home/feng/projects/emacs-packages/emacs-application-framework
npm ERR! command failed
npm ERR! command sh -c node install-node-apps.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/feng/.npm/_logs/2021-07-20T00_12_11_151Z-debug.log
Failed to install dependency with npm.
feng@debian:~/projects/emacs-packages/emacs-application-framework $ 


```

**Comment by tumashu** [comment]
我现在使用的是 debian testing

**Comment by manateelazycat** [comment]
npm升个级？

**Comment by tumashu** [comment]
npm install npm 之后，还会报错， npm install is-svg 之后，就可以正常安装了

**Comment by MatthewZMD** [comment]
不管成功与否，可以pull最新的code在EAF目录再跑一次`npm install`看看吗

**Comment by tumashu** [comment]
```
git reset --hard
HEAD 现在位于 d879710 Remove extra print
feng@debian:~/projects/emacs-packages/emacs-application-framework $ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0
展开对象中: 100% (5/5), 1.16 KiB | 39.00 KiB/s, 完成.
来自 https://github.com/manateelazycat/emacs-application-framework
   d879710..2d8ae17  master     -> origin/master
更新 d879710..2d8ae17
Fast-forward
 install-eaf-mac.sh   |  6 +++---
 install-eaf.sh       | 22 +++++++++++-----------
 install-node-apps.js | 40 ++++++++++++++++++++++++++++------------
 3 files changed, 42 insertions(+), 26 deletions(-)
feng@debian:~/projects/emacs-packages/emacs-application-framework $ ./install-eaf.sh 
[sudo] feng 的密码：
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
aria2 已经是最新版 (1.35.0-3)。
git 已经是最新版 (1:2.30.2-1)。
wmctrl 已经是最新版 (1.07-7+b1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
libglib2.0-dev 已经是最新版 (2.66.8-1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
python3-feedparser 已经是最新版 (5.2.1-3)。
python3-pyqt5 已经是最新版 (5.15.2+dfsg-3)。
python3-pyqt5.qtwebengine 已经是最新版 (5.15.2-2)。
python3-markdown 已经是最新版 (3.3.4-1)。
python3-pygit2 已经是最新版 (1.4.0+dfsg1-1)。
python3-qrcode 已经是最新版 (6.1-2)。
python3-qtconsole 已经是最新版 (5.0.2-2)。
python3-sip 已经是最新版 (4.19.25+dfsg-1)。
libtag1-dev 已经是最新版 (1.11.1+dfsg.1-3)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
Looking in indexes: https://mirrors.163.com/pypi/simple/
Requirement already satisfied: pymupdf in /home/feng/.local/lib/python3.9/site-packages (1.18.13)
Requirement already satisfied: epc in /home/feng/.local/lib/python3.9/site-packages (0.0.5)
Requirement already satisfied: retrying in /home/feng/.local/lib/python3.9/site-packages (1.3.3)
Requirement already satisfied: pytaglib in /usr/lib/python3/dist-packages (0.3.6)
Requirement already satisfied: psutil in /home/feng/.local/lib/python3.9/site-packages (5.8.0)
Requirement already satisfied: sexpdata>=0.0.3 in /home/feng/.local/lib/python3.9/site-packages (from epc) (0.0.3)
Requirement already satisfied: six>=1.7.0 in /usr/lib/python3/dist-packages (from retrying) (1.16.0)
[EAF] Installing npm dependencies...

> emacs-application-framework@1.0.0 postinstall
> node install-node-apps.js

[EAF] Preparing to [npm install] on [app/js-video-player]

up to date, audited 7 packages in 1s

found 0 vulnerabilities
[EAF] [npm install] on [app/js-video-player] has succeeded!
[EAF] Preparing to [npm install] on [app/markdown-previewer]

up to date, audited 246 packages in 2s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[EAF] [npm install] on [app/markdown-previewer] has succeeded!
[EAF] Preparing to [npm install] on [app/image-viewer]

up to date, audited 2 packages in 1s

found 0 vulnerabilities
[EAF] [npm install] on [app/image-viewer] has succeeded!
[EAF] Preparing to [npm install] on [app/terminal]

up to date, audited 68 packages in 1s

found 0 vulnerabilities
[EAF] [npm install] on [app/terminal] has succeeded!
[EAF] Preparing to [npm install] on [app/vue-demo]

up to date, audited 1309 packages in 6s

25 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] [npm install] on [app/vue-demo] has succeeded!
[EAF] Preparing to [npm run build] on [app/vue-demo]

> vue-demo@0.1.0 build
> vue-cli-service build


⠼  Building for production...

 DONE  Compiled successfully in 5360ms                               下午2:11:10

  File                                 Size               Gzipped

  dist/js/chunk-vendors.92c2867a.js    89.66 KiB          32.14 KiB
  dist/js/app.8cb0e284.js              2.87 KiB           1.32 KiB
  dist/css/app.606858ee.css            0.27 KiB           0.20 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
[EAF] [npm run build] on [app/vue-demo] has succeeded!
[EAF] Preparing to [npm install] on [app/system-monitor]

up to date, audited 1325 packages in 6s

15 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] [npm install] on [app/system-monitor] has succeeded!
[EAF] Preparing to [npm run build] on [app/system-monitor]

> system-monitor@0.1.0 build
> vue-cli-service build


 ERROR  Error: CSS minification error: Cannot find module 'is-svg'
 Require stack:
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/postcss-svgo/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano-preset-default/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/config/css.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/Service.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/bin/vue-cli-service.js. File: css/app.46b5b596.css
Error: CSS minification error: Cannot find module 'is-svg'
Require stack:
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/postcss-svgo/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano-preset-default/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/cssnano/dist/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/config/css.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/lib/Service.js
- /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@vue/cli-service/bin/vue-cli-service.js. File: css/app.46b5b596.css
    at /home/feng/projects/emacs-packages/emacs-application-framework/app/system-monitor/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21
    at async Promise.all (index 0)
[EAF] Preparing to [npm install] on [app/music-player]

up to date, audited 1507 packages in 8s

44 packages are looking for funding
  run `npm fund` for details

20 vulnerabilities (6 low, 13 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] [npm install] on [app/music-player] has succeeded!
[EAF] Preparing to [npm run build] on [app/music-player]

> music-player@0.1.0 build
> vue-cli-service build


⠴  Building for production...

 WARNING  Compiled with 2 warnings                                   下午2:11:55

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (253 KiB)
      css/chunk-vendors.98dca482.css
      js/chunk-vendors.1017a703.js
      css/app.7c7accd8.css
      js/app.4cfe2e9a.js


 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                   Size              Gzipped

  dist/js/chunk-vendors.1017a703.js      235.86 KiB        78.54 KiB
  dist/js/app.4cfe2e9a.js                15.02 KiB         4.35 KiB
  dist/css/app.7c7accd8.css              1.49 KiB          0.53 KiB
  dist/css/chunk-vendors.98dca482.css    0.26 KiB          0.17 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
[EAF] [npm run build] on [app/music-player] has succeeded!
[EAF] Preparing to [npm install] on [app/file-manager]

up to date, audited 1309 packages in 9s

25 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] [npm install] on [app/file-manager] has succeeded!
[EAF] Preparing to [npm run build] on [app/file-manager]

> vue-demo@0.1.0 build
> vue-cli-service build


⠹  Building for production...

 DONE  Compiled successfully in 4426ms                               下午2:12:16

  File                                 Size               Gzipped

  dist/js/chunk-vendors.92c2867a.js    89.66 KiB          32.14 KiB
  dist/js/app.f336d461.js              4.01 KiB           1.61 KiB
  dist/css/app.d285c500.css            0.48 KiB           0.24 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
[EAF] [npm run build] on [app/file-manager] has succeeded!
[EAF] Preparing to [npm install] on [app/netease-cloud-music]

up to date, audited 1535 packages in 9s

2 packages are looking for funding
  run `npm fund` for details

22 vulnerabilities (5 low, 16 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[EAF] [npm install] on [app/netease-cloud-music] has succeeded!
[EAF] Preparing to [npm run build] on [app/netease-cloud-music]

> netease-cloud-music@0.1.0 build
> vue-cli-service build


⠇  Building for production...

 DONE  Compiled successfully in 5646ms                               下午2:12:41

  File                                   Size              Gzipped

  dist/js/chunk-vendors.8c54ba53.js      108.23 KiB        38.93 KiB
  dist/js/app.62ff121f.js                16.57 KiB         4.60 KiB
  dist/css/app.f569b004.css              1.33 KiB          0.49 KiB
  dist/css/chunk-vendors.98dca482.css    0.26 KiB          0.17 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
[EAF] [npm run build] on [app/netease-cloud-music] has succeeded!
rebuilt dependencies successfully
[EAF] Failed to install dependencies for the following EAF applications, they may not work correctly!
> app/system-monitor
------
The usage of other EAF applications not listed here may not be affected.
Nonetheless please report the error log to EAF maintainers:
https://github.com/manateelazycat/emacs-application-framework/issues

removed 261 packages, and audited 3 packages in 2m

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[EAF] eaf-install.sh finished.
feng@debian:~/projects/emacs-packages/emacs-application-framework $ 


```

**Comment by MatthewZMD** [comment]
`npm install is-svg`后还是没法`npm run build`?

**Comment by tumashu** [comment]
npm install is-svg 之后，install-eaf.sh 可以安装完成，没有报错

**Comment by MatthewZMD** [comment]
抽空试试最新版

**Comment by tumashu** [comment]
可以了，感谢！
