### ISSUE TITLE
`install-eaf.sh` got No prebuilt binaries found

### ISSUE THREAD

**Issue by thyecust** [manateelazycat/emacs-application-framework#718]
**Describe the bug**
When run `./install-eaf.sh`, got

```
:: 正在同步软件包数据库...
 core 已经是最新版本
 extra 已经是最新版本
 community 已经是最新版本
 multilib 已经是最新版本
 archlinuxcn 已经是最新版本
警告：git-2.32.0-1 已经为最新 -- 跳过
警告：nodejs-16.4.2-1 已经为最新 -- 跳过
警告：npm-7.17.0-1 已经为最新 -- 跳过
警告：python-pyqt5-5.15.4-1 已经为最新 -- 跳过
警告：python-pyqt5-sip-12.9.0-1 已经为最新 -- 跳过
警告：python-pyqt5-webengine-5.15.4-1 已经为最新 -- 跳过
警告：wmctrl-1.07-6 已经为最新 -- 跳过
警告：python-qrcode-6.1-6 已经为最新 -- 跳过
警告：aria2-1.35.0-2 已经为最新 -- 跳过
警告：python-qtconsole-5.1.1-1 已经为最新 -- 跳过
警告：taglib-1.12-1 已经为最新 -- 跳过
 今日无事可做
警告：filebrowser-bin-2.15.0-1 已经为最新 -- 重新安装
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) filebrowser-bin-2.15.0-1

全部安装大小：  31.61 MiB
净更新大小：     0.00 MiB

:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                                   [##################################] 100%
(1/1) 正在检查软件包完整性                                     [##################################] 100%
(1/1) 正在加载软件包文件                                       [##################################] 100%
(1/1) 正在检查文件冲突                                         [##################################] 100%
(1/1) 正在检查可用存储空间                                     [##################################] 100%
:: 正在处理软件包的变化...
(1/1) 正在重新安装 filebrowser-bin                             [##################################] 100%

If you upgrade the filebrowser from 1.x
You must need to read the: https://docs.filebrowser.xyz/upgrade-from-1.x
And the systemd unit and config file also need to be changed by yourself.

More: https://github.com/filebrowser/filebrowser
      https://docs.filebrowser.xyz/

:: 正在运行事务后钩子函数...
(1/2) Reloading system manager configuration...
(2/2) Arming ConditionNeedsUpdate...
Installing npm dependencies...

> emacs-application-framework@1.0.0 postinstall
> node install-node-apps.js


up to date, audited 7 packages in 3s

found 0 vulnerabilities

up to date, audited 246 packages in 3s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

up to date, audited 2 packages in 2s

found 0 vulnerabilities
npm ERR! code 1
npm ERR! path /home/tianh/.emacs.d/site-lisp/emacs-application-framework/app/terminal/node_modules/node-pty-prebuilt-multiarch
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node scripts/install.js
npm ERR! prebuild-install WARN install Request timed out
npm ERR! node:internal/modules/cjs/loader:930
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'env-paths'
npm ERR! Require stack:
npm ERR! - /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:772:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:93:18)
npm ERR!     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:7:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1095:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [ '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js' ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tianh/.npm/_logs/2021-07-22T06_53_17_387Z-debug.log
node:child_process:903
    throw err;
    ^

Error: Command failed: npm install
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at installNodeApps (/home/tianh/.emacs.d/site-lisp/emacs-application-framework/install-node-apps.js:10:9)
    at Object.<anonymous> (/home/tianh/.emacs.d/site-lisp/emacs-application-framework/install-node-apps.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11925,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /home/tianh/.emacs.d/site-lisp/emacs-application-framework
npm ERR! command failed
npm ERR! command sh -c node install-node-apps.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tianh/.npm/_logs/2021-07-22T06_53_17_410Z-debug.log
Failed to install dependency with npm.
```

`/home/tianh/.npm/_logs/2021-07-22T06_53_17_387Z-debug.log`

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
1 info using npm@7.20.0
2 info using node@v16.4.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/tianh/.emacs.d/site-lisp/emacs-application-framework/app/terminal/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/tianh/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 1ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 12ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 timing idealTree:init Completed in 47ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 timing idealTree:#root Completed in 1ms
32 timing idealTree:buildDeps Completed in 1ms
33 timing idealTree:fixDepFlags Completed in 0ms
34 timing idealTree Completed in 49ms
35 timing reify:loadTrees Completed in 52ms
36 timing reify:diffTrees Completed in 2ms
37 silly reify moves {}
38 timing reify:retireShallow Completed in 1ms
39 timing reify:createSparse Completed in 6ms
40 timing reify:loadBundles Completed in 0ms
41 silly audit bulk request {
41 silly audit   'ansi-regex': [ '2.1.1' ],
41 silly audit   aproba: [ '1.2.0' ],
41 silly audit   'are-we-there-yet': [ '1.1.5' ],
41 silly audit   'base64-js': [ '1.5.1' ],
41 silly audit   bl: [ '4.1.0' ],
41 silly audit   'readable-stream': [ '3.6.0', '2.3.7' ],
41 silly audit   buffer: [ '5.7.1' ],
41 silly audit   chownr: [ '1.1.4' ],
41 silly audit   'code-point-at': [ '1.1.0' ],
41 silly audit   'console-control-strings': [ '1.1.0' ],
41 silly audit   'core-util-is': [ '1.0.2' ],
41 silly audit   'decompress-response': [ '4.2.1' ],
41 silly audit   'deep-extend': [ '0.6.0' ],
41 silly audit   delegates: [ '1.0.0' ],
41 silly audit   'detect-libc': [ '1.0.3' ],
41 silly audit   'end-of-stream': [ '1.4.4' ],
41 silly audit   'expand-template': [ '2.0.3' ],
41 silly audit   'fs-constants': [ '1.0.0' ],
41 silly audit   gauge: [ '2.7.4' ],
41 silly audit   'github-from-package': [ '0.0.0' ],
41 silly audit   'has-unicode': [ '2.0.1' ],
41 silly audit   ieee754: [ '1.2.1' ],
41 silly audit   inherits: [ '2.0.4' ],
41 silly audit   ini: [ '1.3.8' ],
41 silly audit   'is-fullwidth-code-point': [ '1.0.0' ],
41 silly audit   isarray: [ '1.0.0' ],
41 silly audit   'mimic-response': [ '2.1.0' ],
41 silly audit   minimist: [ '1.2.5' ],
41 silly audit   'mkdirp-classic': [ '0.5.3' ],
41 silly audit   nan: [ '2.14.2' ],
41 silly audit   'napi-build-utils': [ '1.0.2' ],
41 silly audit   'node-abi': [ '2.19.3' ],
41 silly audit   'node-pty-prebuilt-multiarch': [ '0.10.0' ],
41 silly audit   'noop-logger': [ '0.1.1' ],
41 silly audit   npmlog: [ '4.1.2' ],
41 silly audit   'number-is-nan': [ '1.0.1' ],
41 silly audit   'object-assign': [ '4.1.1' ],
41 silly audit   once: [ '1.4.0' ],
41 silly audit   'prebuild-install': [ '6.0.1' ],
41 silly audit   'process-nextick-args': [ '2.0.1' ],
41 silly audit   pump: [ '3.0.0' ],
41 silly audit   rc: [ '1.2.8' ],
41 silly audit   'safe-buffer': [ '5.1.2' ],
41 silly audit   semver: [ '5.7.1' ],
41 silly audit   'set-blocking': [ '2.0.0' ],
41 silly audit   'signal-exit': [ '3.0.3' ],
41 silly audit   'simple-concat': [ '1.0.1' ],
41 silly audit   'simple-get': [ '3.1.0' ],
41 silly audit   string_decoder: [ '1.1.1' ],
41 silly audit   'string-width': [ '1.0.2' ],
41 silly audit   'strip-ansi': [ '3.0.1' ],
41 silly audit   'strip-json-comments': [ '2.0.1' ],
41 silly audit   'tar-fs': [ '2.1.1' ],
41 silly audit   'tar-stream': [ '2.2.0' ],
41 silly audit   'tunnel-agent': [ '0.6.0' ],
41 silly audit   'util-deprecate': [ '1.0.2' ],
41 silly audit   'which-pm-runs': [ '1.0.0' ],
41 silly audit   'wide-align': [ '1.1.3' ],
41 silly audit   wrappy: [ '1.0.2' ],
41 silly audit   ws: [ '7.4.6' ],
41 silly audit   xterm: [ '4.10.0' ],
41 silly audit   'xterm-addon-attach': [ '0.5.0' ],
41 silly audit   'xterm-addon-fit': [ '0.3.0' ],
41 silly audit   'xterm-addon-search': [ '0.5.0' ],
41 silly audit   'xterm-addon-web-links': [ '0.2.1' ]
41 silly audit }
42 timing reifyNode:node_modules/wrappy Completed in 190ms
43 timing reifyNode:node_modules/wide-align Completed in 191ms
44 timing reifyNode:node_modules/which-pm-runs Completed in 191ms
45 timing reifyNode:node_modules/strip-json-comments Completed in 191ms
46 timing reifyNode:node_modules/strip-ansi Completed in 191ms
47 timing reifyNode:node_modules/string-width Completed in 191ms
48 timing reifyNode:node_modules/simple-get Completed in 191ms
49 timing reifyNode:node_modules/process-nextick-args Completed in 192ms
50 timing reifyNode:node_modules/once Completed in 192ms
51 timing reifyNode:node_modules/number-is-nan Completed in 192ms
52 timing reifyNode:node_modules/object-assign Completed in 192ms
53 timing reifyNode:node_modules/mkdirp-classic Completed in 192ms
54 timing reifyNode:node_modules/is-fullwidth-code-point Completed in 191ms
55 timing reifyNode:node_modules/ini Completed in 191ms
56 timing reifyNode:node_modules/end-of-stream Completed in 193ms
57 timing reifyNode:node_modules/has-unicode Completed in 193ms
58 timing reifyNode:node_modules/code-point-at Completed in 193ms
59 timing reifyNode:node_modules/chownr Completed in 192ms
60 timing reifyNode:node_modules/aproba Completed in 192ms
61 timing reifyNode:node_modules/ansi-regex Completed in 193ms
62 timing reifyNode:node_modules/tunnel-agent Completed in 196ms
63 timing reifyNode:node_modules/set-blocking Completed in 196ms
64 timing reifyNode:node_modules/mimic-response Completed in 196ms
65 timing reifyNode:node_modules/inherits Completed in 195ms
66 timing reifyNode:node_modules/fs-constants Completed in 195ms
67 timing reifyNode:node_modules/ieee754 Completed in 195ms
68 timing reifyNode:node_modules/console-control-strings Completed in 196ms
69 timing reifyNode:node_modules/decompress-response Completed in 196ms
70 timing reifyNode:node_modules/util-deprecate Completed in 198ms
71 timing reifyNode:node_modules/signal-exit Completed in 198ms
72 timing reifyNode:node_modules/expand-template Completed in 197ms
73 timing reifyNode:node_modules/base64-js Completed in 196ms
74 timing reifyNode:node_modules/string_decoder Completed in 200ms
75 timing reifyNode:node_modules/simple-concat Completed in 200ms
76 timing reifyNode:node_modules/safe-buffer Completed in 199ms
77 timing reifyNode:node_modules/pump Completed in 199ms
78 timing reifyNode:node_modules/npmlog Completed in 200ms
79 timing reifyNode:node_modules/napi-build-utils Completed in 200ms
80 timing reifyNode:node_modules/deep-extend Completed in 199ms
81 timing reifyNode:node_modules/isarray Completed in 200ms
82 timing reifyNode:node_modules/core-util-is Completed in 202ms
83 timing reifyNode:node_modules/delegates Completed in 202ms
84 timing reifyNode:node_modules/noop-logger Completed in 203ms
85 timing reifyNode:node_modules/detect-libc Completed in 203ms
86 timing reifyNode:node_modules/tar-stream Completed in 205ms
87 timing reifyNode:node_modules/semver Completed in 205ms
88 timing reifyNode:node_modules/are-we-there-yet Completed in 203ms
89 timing reifyNode:node_modules/buffer Completed in 204ms
90 timing reifyNode:node_modules/xterm-addon-attach Completed in 209ms
91 timing reifyNode:node_modules/github-from-package Completed in 207ms
92 timing reifyNode:node_modules/xterm-addon-web-links Completed in 210ms
93 timing reifyNode:node_modules/rc Completed in 208ms
94 timing reifyNode:node_modules/node-abi Completed in 210ms
95 timing reifyNode:node_modules/bl Completed in 208ms
96 timing reifyNode:node_modules/xterm-addon-fit Completed in 212ms
97 timing reifyNode:node_modules/prebuild-install Completed in 212ms
98 timing reifyNode:node_modules/xterm-addon-search Completed in 215ms
99 timing reifyNode:node_modules/minimist Completed in 214ms
100 timing reifyNode:node_modules/gauge Completed in 213ms
101 timing reifyNode:node_modules/ws Completed in 218ms
102 timing reifyNode:node_modules/readable-stream Completed in 219ms
103 timing reifyNode:node_modules/tar-stream/node_modules/readable-stream Completed in 221ms
104 timing reifyNode:node_modules/bl/node_modules/readable-stream Completed in 218ms
105 timing reifyNode:node_modules/tar-fs Completed in 222ms
106 timing reifyNode:node_modules/nan Completed in 228ms
107 timing reifyNode:node_modules/xterm Completed in 253ms
108 timing reifyNode:node_modules/node-pty-prebuilt-multiarch Completed in 259ms
109 timing reify:unpack Completed in 261ms
110 timing reify:unretire Completed in 0ms
111 timing build:queue Completed in 1ms
112 timing build:link:node_modules/detect-libc Completed in 1ms
113 timing build:link:node_modules/rc Completed in 1ms
114 timing build:link:node_modules/prebuild-install Completed in 1ms
115 timing build:link:node_modules/semver Completed in 1ms
116 timing build:link Completed in 2ms
117 info run node-pty-prebuilt-multiarch@0.10.0 install node_modules/node-pty-prebuilt-multiarch prebuild-install || node scripts/install.js
118 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1385ms
119 timing auditReport:getReport Completed in 1387ms
120 silly audit report {}
121 timing auditReport:init Completed in 0ms
122 timing reify:audit Completed in 1388ms
123 info run node-pty-prebuilt-multiarch@0.10.0 install { code: 1, signal: null }
124 timing reify:rollback:createSparse Completed in 63ms
125 timing reify:rollback:retireShallow Completed in 0ms
126 timing command:install Completed in 30894ms
127 verbose stack Error: command failed
127 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
127 verbose stack     at ChildProcess.emit (node:events:394:28)
127 verbose stack     at maybeClose (node:internal/child_process:1067:16)
127 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
128 verbose pkgid node-pty-prebuilt-multiarch@0.10.0
129 verbose cwd /home/tianh/.emacs.d/site-lisp/emacs-application-framework/app/terminal
130 verbose Linux 5.10.49-1-MANJARO
131 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
132 verbose node v16.4.2
133 verbose npm  v7.20.0
134 error code 1
135 error path /home/tianh/.emacs.d/site-lisp/emacs-application-framework/app/terminal/node_modules/node-pty-prebuilt-multiarch
136 error command failed
137 error command sh -c prebuild-install || node scripts/install.js
138 error prebuild-install WARN install Request timed out
138 error node:internal/modules/cjs/loader:930
138 error   throw err;
138 error   ^
138 error
138 error Error: Cannot find module 'env-paths'
138 error Require stack:
138 error - /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js
138 error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
138 error     at Function.Module._load (node:internal/modules/cjs/loader:772:27)
138 error     at Module.require (node:internal/modules/cjs/loader:999:19)
138 error     at require (node:internal/modules/cjs/helpers:93:18)
138 error     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:7:18)
138 error     at Module._compile (node:internal/modules/cjs/loader:1095:14)
138 error     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
138 error     at Module.load (node:internal/modules/cjs/loader:975:32)
138 error     at Function.Module._load (node:internal/modules/cjs/loader:816:12)
138 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
138 error   code: 'MODULE_NOT_FOUND',
138 error   requireStack: [ '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js' ]
138 error }
139 verbose exit 1
```

`home/tianh/.npm/_logs/2021-07-22T06_53_17_410Z-debug.log`

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
1 info using npm@7.20.0
2 info using node@v16.4.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/tianh/.emacs.d/site-lisp/emacs-application-framework/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/tianh/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 12ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 13ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 timing idealTree:#root Completed in 0ms
32 timing idealTree:buildDeps Completed in 1ms
33 timing idealTree:fixDepFlags Completed in 0ms
34 timing idealTree Completed in 15ms
35 timing reify:loadTrees Completed in 16ms
36 timing reify:diffTrees Completed in 0ms
37 silly reify moves {}
38 timing reify:retireShallow Completed in 0ms
39 timing reify:createSparse Completed in 1ms
40 timing reify:loadBundles Completed in 0ms
41 silly audit bulk request { '@mozilla/readability': [ '0.4.1' ], darkreader: [ '4.9.34' ] }
42 timing reifyNode:node_modules/@mozilla/readability Completed in 52ms
43 timing reifyNode:node_modules/darkreader Completed in 52ms
44 timing reify:unpack Completed in 52ms
45 timing reify:unretire Completed in 0ms
46 timing build:queue Completed in 1ms
47 timing build:deps Completed in 1ms
48 timing build Completed in 1ms
49 timing reify:build Completed in 1ms
50 timing reify:trash Completed in 0ms
51 timing reify:save Completed in 2ms
52 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1320ms
53 timing auditReport:getReport Completed in 1321ms
54 silly audit report {}
55 timing auditReport:init Completed in 0ms
56 timing reify:audit Completed in 1322ms
57 timing reify Completed in 1355ms
58 timing command:install Completed in 40579ms
59 verbose stack Error: command failed
59 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
59 verbose stack     at ChildProcess.emit (node:events:394:28)
59 verbose stack     at maybeClose (node:internal/child_process:1067:16)
59 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
60 verbose pkgid emacs-application-framework@1.0.0
61 verbose cwd /home/tianh/.emacs.d/site-lisp/emacs-application-framework
62 verbose Linux 5.10.49-1-MANJARO
63 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
64 verbose node v16.4.2
65 verbose npm  v7.20.0
66 error code 1
67 error path /home/tianh/.emacs.d/site-lisp/emacs-application-framework
68 error command failed
69 error command sh -c node install-node-apps.js
70 verbose exit 1
```

**Versions (please complete the following info):**
```
Manjaro Linux 40.2.0
node v16.4.2
npm 7.20.0
```

**Additional context**

This is a new install operating system. I was wondering whether there is anything need to install before eaf but emacs.

**Comment by thyecust** [comment]
- 安装 node 应用，安装声明在 `package.json` 的 `apps` 中的 package
    - 第一个是 `app/js-video-player`，audited 7 packages in 2s
    - `app/markdown-previewer`，audited 246 packages in 2s
    - `app/image-viewer`，2 packages in 1s
    - `app/terminal`，报错 `Cannot find module 'env-paths`
- 安装 vue 应用
- rebuild node 应用

**Comment by thyecust** [comment]
"node-pty-prebuilt-multiarch": "^0.10.1-pre.4" will work

**Comment by thyecust** [comment]
this is just a npm version problem, see https://www.npmjs.com/package/semver for details. node-pty-prebuilt-multiarch current version is 0.10.1-pre.4, which not satisfying ^0.10.0 (can't match -pre) in packages.json. I'll close this.
