### ISSUE TITLE
can't run eaf-terminal in wayland

### ISSUE THREAD

**Issue by titaniumbones** [manateelazycat/emacs-application-framework#80]
I'm not sure if you intend to support running under wayland at all, but while most of the existing apps will at least open (though they seem to be integrated into emacs), eap-open-terminal fails with:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
EAF process start.
No data in session file, no need restore session.
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x00000002), sequence_number = 13, major_opcode = 7, minor_opcode = 0
CameraBin error: "Internal data stream error."
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
EAF process start.
Traceback (most recent call last):
  File "/home/matt/src/emacs-application-framework/eaf.py", line 114, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/matt/src/emacs-application-framework/eaf.py", line 126, in create_buffer
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/matt/src/emacs-application-framework/app/terminal/buffer.py", line 24, in <module>
    import QTermWidget
ModuleNotFoundError: No module named 'QTermWidget'
```

I've tried the following: 
in Emacs (and even inside a `let` statement in a modified `eap-start-process`):

```emacs-lisp
(setenv "QT_QPA_PLATFORM" "wayland")
```
in my `.zshenv`:
```sh
export QT_QPA_PLATFORM=wayland
```
Not sure what comes next, but htanks for htis interesting tool.

**Comment by titaniumbones** [comment]
I'm afraid I can't read #45, but maybe it's saying "won't support wayland", in which case I guess this would be a dupe.

**Comment by MatthewZMD** [comment]
Yes it indeed says Wayland is not supported, I don't think @manateelazycat is using wayland himself. Maybe if you can make it work yourself and submit a PR

**Comment by manateelazycat** [comment]
First, EAF not support Wayland, because it use XReparent tech that wayland not support.

Second, you problem is python library qtermwidget is not install in your system.

**Comment by manateelazycat** [comment]
Install QTermWidget python module, use below command：

```Bash
git clone https://github.com/lxqt/qtermwidget.git --depth=1
mkdir bulid && cd build
cmake .. -DQTERMWIDGET_BUILD_PYTHON_BINDING=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr
make
sudo make install
```
